proxy:
  title: Let's Try Out ShinyProxy
  logo-url: http://www.openanalytics.eu/sites/www.openanalytics.eu/themes/oa/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: none
  # Docker configuration
  docker:
    cert-path: /home/none
    url: http://localhost:2375
    port-range-start: 20000
  specs:
  - id: euler
    display-name: Euler's number
    container-cmd: ["R", "-e", "shiny::runApp('/root/euler')"]
    container-image: openanalytics/shinyproxy-template
    access-groups: scientists
  - id: eruption
    display-name: Eruption Histogram
    container-cmd: ["R", "-e", "shiny::runApp('/root/eruption')"]
    container-image: eruption_image
    access-groups: scientists

logging:
  file:
    shinyproxy.log